apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.name" . }}-loki-credentials
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "controller.labels" . | nindent 4 }}
stringData:
  loki-url: {{ required "loki.url is required" .Values.loki.url | quote }}
  loki-org-id: {{ .Values.loki.orgId | default "" | quote }}
  loki-username: {{ .Values.loki.auth.username | default "" | quote }}
  loki-password: {{ .Values.loki.auth.password | default "" | quote }}
type: Opaque
