apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}-loki-credentials
  labels:
  {{- include "controller.labels" . | nindent 4 }}
stringData:
  cluster-name: {{ required "loki.clusterName is required" .Values.loki.clusterName
    | quote }}
  loki-host: {{ required "loki.host is required" .Values.loki.host
    | quote }}
  loki-password: {{ required "loki.password is required" .Values.loki.password
    | quote }}
  loki-port: {{ required "loki.port is required" .Values.loki.port
    | quote }}
  loki-tenant-id: {{ required "loki.tenantId is required" .Values.loki.tenantId
    | quote }}
  loki-tls: {{ required "loki.tls is required" .Values.loki.tls
    | quote }}
  loki-tls-verify: {{ required "loki.tlsVerify is required" .Values.loki.tlsVerify
    | quote }}
  loki-user: {{ required "loki.user is required" .Values.loki.user
    | quote }}
type: Opaque
