apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}-loki-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    kentra.sh/resource-type: "loki-credentials"
stringData:
  loki-host: {{ required "loki.host is required" .Values.loki.host | quote }}
  loki-port: {{ .Values.loki.port | default "80" | quote }}
  loki-tls: {{ .Values.loki.tls | default "off" | quote }}
  loki-tls-verify: {{ .Values.loki.tlsVerify | default "off" | quote }}
  loki-tenant-id: {{ .Values.loki.tenantId | default "" | quote }}
  loki-user: {{ .Values.loki.auth.username | default "" | quote }}
  loki-password: {{ .Values.loki.auth.password | default "" | quote }}
  cluster-name: {{ .Values.loki.clusterName | default "default" | quote }}
type: Opaque
