apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: controller
  {{- include "controller.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
