apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-specs
  namespace: kttack-system
data:
  tools: |
    nmap:
      type: "enumeration"
      image: "instrumentisto/nmap:latest"
      commandTemplate: "/usr/bin/nmap {{.Args}} {{.Target}}"
      capabilities:
        add:
          - NET_RAW
    nikto:
      type: "scanning"
      image: "ghcr.io/sullo/nikto:latest"
      commandTemplate: "/nikto -h {{.Target}} {{.Args}}"
      capabilities:
        add: []
    masscan:
      # masscan needs raw sockets
      type: "enumeration"
      image: "robertdavidgraham/masscan:latest"
      commandTemplate: "/bin/masscan {{.Args}} {{.Target}}"
      capabilities:
        add:
          - NET_RAW
    gobuster:
      # gobuster's container usually exposes gobuster as entrypoint
      type: "scanning"
      image: "aoighost/gobuster"
      commandTemplate: "/go/bin/gobuster {{.Args}} {{.Target}}"
      capabilities:
        add: []
    wpscan:
      # WPScan usually runs via ruby wpscan; pass host/flags as args
      type: "scanning"
      image: "wpscanteam/wpscan:latest"
      commandTemplate: "/wpscan --url {{.Target}} {{.Args}}"
      capabilities:
        add: []
    sqlmap:
      # sqlmap image usually exposes sqlmap as entrypoint
      type: "exploitation"
      image: "sqlmapproject/sqlmap:latest"
      commandTemplate: "/sqlmap -u {{.Target}} {{.Args}}"
      capabilities:
        add: []
    feroxbuster:
      type: "scanning"
      image: "epi052/feroxbuster"
      commandTemplate: "/feroxbuster -u {{.Target}} {{.Args}}"
      capabilities:
        add: []
    dirsearch:
      type: "scanning"
      image: "maurosoria/dirsearch:latest"
      commandTemplate: "/dirsearch -u {{.Target}} {{.Args}}"
      capabilities:
        add: []