---
apiVersion: kentra.sh/v1alpha1
kind: Enumeration
metadata:
  name: rustscan-multi-target
  namespace: kentra-system
spec:
  args:
    - '--ulimit'
    - '5000'
  category: Reconnaissance
  debug: true
  periodic: false
  targetPool: multi-host-pool
  tool: rustscan