---
apiVersion: kentra.sh/v1alpha1
kind: Enumeration
metadata:
  name: nmap-scan-ports
  namespace: kentra-system
spec:
  tool: nmap
  targetPool: nmap-scan-targets
  category: Reconnaissance
  debug: false
  periodic: false