---
apiVersion: kttack.io/v1alpha1
kind: Enumeration
metadata:
  name: nmap-scan-ports
  namespace: kttack-system
spec:
  tool: nmap
  targetGroup: nmap-scan-targets
  category: Reconnaissance
  debug: false
  periodic: false