apiVersion: kentra.sh/v1alpha1
kind: Enumeration
metadata:
  name: feroxbuster-web-scan
  namespace: kentra-system
spec:
  args:
    - '-d'
    - '3'
    - '-t'
    - '50'
    - '-C'
    - '404'
    - '-w /config/raft-medium-directories.txt'
  category: Web Application Security
  debug: true
  periodic: false
  storagePool: web-wordlists
  targetPool: web-targets
  tool: feroxbuster
