apiVersion: kentra.sh/v1alpha1
kind: Osint
metadata:
  name: osint-usernames-sherlock
  namespace: kentra-system
spec:
  assetPool: username-targets
  debug: true
  tool: sherlock
---
apiVersion: kentra.sh/v1alpha1
kind: Osint
metadata:
  name: osint-usernames-maigret
  namespace: kentra-system
spec:
  assetPool: username-targets
  debug: true
  tool: maigret