apiVersion: kttack.io/v1alpha1
kind: Osint
metadata:
  name: osint-usernames-sherlock
  namespace: kttack-system
spec:
  assetPool: username-targets
  debug: true
  tool: sherlock
---
apiVersion: kttack.io/v1alpha1
kind: Osint
metadata:
  name: osint-usernames-maigret
  namespace: kttack-system
spec:
  assetPool: username-targets
  debug: true
  tool: maigret