apiVersion: kentra.sh/v1alpha1
kind: Osint
metadata:
  name: twint-multi-asset
  namespace: kentra-system
spec:
  tool: twint
  assetPool: username-targets
  category: username-enumeration
  periodic: false
  debug: true