apiVersion: kentra.sh/v1alpha1
kind: Osint
metadata:
  name: osint-sample
  namespace: kentra-system
spec:
  tool: sherlock
  assetPool: username-targets
  category: username-enumeration
  periodic: false
  debug: true