---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kttack.io
  resources:
  - enumerations
  - livenesses
  - securityattacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kttack.io
  resources:
  - enumerations/finalizers
  - livenesses/finalizers
  - securityattacks/finalizers
  verbs:
  - update
- apiGroups:
  - kttack.io
  resources:
  - enumerations/status
  - livenesses/status
  - securityattacks/status
  verbs:
  - get
  - patch
  - update
