---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kentra.sh
  resources:
  - assetpools
  - enumerations
  - exploits
  - livenesses
  - osints
  - securityattacks
  - storagepools
  - targetpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kentra.sh
  resources:
  - assetpools/finalizers
  - enumerations/finalizers
  - exploits/finalizers
  - livenesses/finalizers
  - osints/finalizers
  - securityattacks/finalizers
  - storagepools/finalizers
  - targetpools/finalizers
  verbs:
  - update
- apiGroups:
  - kentra.sh
  resources:
  - assetpools/status
  - enumerations/status
  - exploits/status
  - livenesses/status
  - osints/status
  - securityattacks/status
  - storagepools/status
  - targetpools/status
  verbs:
  - get
  - patch
  - update
