apiVersion: kttack.io/v1alpha1
kind: Liveness
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/managed-by: kustomize
  name: liveness-sample
spec:
  target: 8.8.8.8
  tool: ping
  periodic: true
  schedule: "*/5 * * * *"
