---
apiVersion: kentra.sh/v1alpha1
kind: TargetPool
metadata:
  name: multi-host-pool
  namespace: kentra-system
spec:
  targets: 
    - type: "cidr"
    - 192.168.2.0/24
    - 192.168.1.201/32
    - 192.168.1.202/32
  port: "1-10000"
  description: "Three specific hosts for comprehensive port scanning"