apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../default

namespace: kentra-system

images:
- name: ghcr.io/kentrasecurity/controller
  newName: ghcr.io/kentrasecurity/controller
  newTag: latest
