---
apiVersion: kentra.sh/v1alpha1
kind: TargetPool
metadata:
  name: targetpool-test
  namespace: kentra-system
spec:
  description: "Target group for web application security testing with feroxbuster and dirbuster"
  targets:  
    - name: test1
      endpoint: 
        - "192.168.2.0"
        - "192.168.1.0"
      port:
        - "80"
---
apiVersion: kentra.sh/v1alpha1
kind: Enumeration
metadata:
  name: feroxbuster-web-scan
  namespace: kentra-system
spec:
  tool: feroxbuster
  targetPool: targetpool-test
  storagePool: web-wordlists
  category: "Web Application Security"
  args:
    - "-d"
    - "3"
    - "-t"
    - "50"
    - "-C"
    - "404"
    - "-w"
    - "/config/raft-medium-directories.txt"
  debug: true
  periodic: false
---
apiVersion: kentra.sh/v1alpha1
kind: StoragePool
metadata:
  name: web-wordlists
  namespace: kentra-system
spec:
  files:
  - raft-medium-directories.txt
  - raft-large-directories-lowercase.txt
  description: "Storage group for web enumeration wordlists"
      
