apiVersion: kentra.sh/v1alpha1
kind: AssetPool
metadata:
  name: contacts
  namespace: kentra-system
spec:
  description: Pool of assets
  asset:
    username:
      - john
      - doe
    email:
      - john@gmail.com
    phone:
      - '+1234567890'
    uri:
      - 'https://github.com/trufflesecurity/trufflehog.git'
      - 'https://github.com/megadose/holehe.git'
    description: john