apiVersion: kentra.sh/v1alpha1
kind: TargetPool
metadata:
  name: nmap-direct-target
  namespace: kentra-system
spec:
  target:
    ip:
      - "192.168.1.0/24"
  port: "22,80,443"
  description: "Direct target for nmap"