apiVersion: kttack.io/v1alpha1
kind: AssetPool
metadata:
  name: username-targets
  namespace: kttack-system
spec:
  description: "Pool of username targets for OSINT"
  items:
    - type: username
      value: root00leo